# Site
repository: kunalrdeshmukh/kunalrdeshmukh.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kunal Deshmukh
title: Data Engineer
email: kunaldeshmukh27@gmail.com
website: www.kunaldeshmukh.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  kunalrdeshmukh
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: krdeshmukh
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: https://scholar.google.com/
  icon: fas fa-user-graduate
  url: https://scholar.google.com/citations?user=K06WfEEAAAAJ
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/IMG.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi! I am Kunal and I am a Data Enginner. I build pipelines - from the lake to a container (or pod) and back and help find interesting stuff in data. 
  
  Previously, I have worked as a Software Developer and also wore a Data Scientist hat during my internship.


content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Meta Platforms
        link: meta.com
        link_text: meta.com
        sub_title: Data Engineer
        caption: March 2022 - Current
        # quote: >
        #   Solving 21st century problems by 
        description: | # this will include new lines to allow paragraphs
            Learning new things! Still a newbie here.

      - layout: left
        title: Ericsson
        link: ericsson.com
        link_text: Ericsson.com
        sub_title: Data Engineer
        caption: July 2019 - March 2022
        # quote: >
        #   Solving 21st century problems by 
        description: | # this will include new lines to allow paragraphs
            I worked here in a team with Data Scientiests and Machine Learning Enginners to develop end to end Machine Learning applications that allow users in to easily deploy, use, retrain and monitor machine learning models. 
      
      - layout: left
        title: Infosys
        link: infosys.com
        link_text: Infosys.com
        sub_title: Systems Engineer
        caption: Jan 2015 - June 2017
        # quote: >
        #   Solving 21st century problems by 
        description: | # this will include new lines to allow paragraphs
            I learned here to fix enterprise software applications in production and worked with other talented software developers to maintain and enhance applications. Major part of my work was in Java and Oracle DB. I was introduced to the world of Python here and spent lot of time writing scripts to automate work and some Data analytics. 

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: San Jose State University (SJSU)
        caption: 2017 - 2029
        sub_title: MSc Computer Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
            Started post graduation after a brief staint in industry. I focused on Data Science and got opportuinity to apply tricks during my work as a Research assistant. 
            
            During free time, established and contributed to ML club for students at SJSU. 

      - layout: left
        title: Mumbai University
        caption: 2010 - 2014
        sub_title: BE (Computer Engg)
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
            I was introduced to Software development, Databases, Networking .. etc., along with many other essential life skills here. I learned to manage multiple projects and assignments at once and managed to navigate though tough deadlines by burning midnight oil. 

            Apart from studies, participated in Robotics workshops and hackethons. I was IT Head and then secretary of the local chapter of Computer Society of India(CSI).



  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
        - Residual CNN Image Compression            [Published in LNCS Vol. 11845, pp 371 - 382 ](https://link.springer.com/chapter/10.1007/978-3-030-33723-0_30)
          
          Designed and implemented image compression framework based on fully convolutional neural networks and GANs. Achieved SSIM of 0.86 after 4x compression in size.
        
        - The Nubo Virtual Services Marketplace     [arXiv: 1909.04934](https://arxiv.org/abs/1909.04934)

          Contributed to profile analysis and scalability study for Nubo distributed marketplace with Ethereum based Quorum blockchain.


  - title: Blogs
    layout: text
    content: | # this will include new lines to allow paragraphs
        - [Collaborative Filtering in Recommendation Systems](https://medium.com/kunalrdeshmukh/collaborative-filtering-in-recommendation-systems-2fa49be8f518)
                  
        - [FTP server with Raspberry PI and HDD](https://medium.com/kunalrdeshmukh/ftp-server-with-raspberry-pi-and-hdd-3c10ce95f2d4)

        - [Optimizing AI program execution in the cloud](https://www.ericsson.com/en/blog/2018/7/optimizing-ai-program-execution-in-the-cloud)

  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
